### ISSUE TITLE
Add NN training demo to the gallery

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/GenieFrameworkDocs#16]
https://github.com/BuiltWithGenie/NNtraining

**Comment by ms10596** [comment]
You've already added it, right?
![image](https://github.com/GenieFramework/GenieFrameworkDocs/assets/25807671/f987384e-af4b-40ee-8620-10f74864ee96)

**Comment by PGimenez** [comment]
Yes, I only left it open because it's still not hosted on Genie Cloud. We're having some issues with that. I'll just remove the Open app link and close this
