### ISSUE TITLE
Review genieframework guides for Genie.jl

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/GenieFrameworkDocs#3]
Need to go through the guides and determine:
- If they are up to date
- If their content belongs to the reference docs or tutorials sections

Other tasks:
- Change headings to enable TOC display
- Check for broken links or images

**Comment by ms10596** [comment]
For some reason, all links are redirecting to 404 page
![image](https://github.com/GenieFramework/GenieFrameworkDocs/assets/25807671/f782b94e-3c02-4755-98b3-ee989cd55609)
Should I try to fix them?

**Comment by PGimenez** [comment]
No need, this page is from an older version where I just added all the content from genieframework.com/docs into the guides section. I'm writing a new guides index page (#42)
