### ISSUE TITLE
Deploying to a server

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/GenieFrameworkDocs#38]
How to deploy an app to a server without using containers.

1. Download and instantiate Genie app
2. Configure as a service with systemctl or with @vrkansagara's guide
3. Reverse proxy with NGINX

Template: https://genieframework.com/docs/genie/v5.11/tutorials/Deploying-Genie-Server-Apps-with-Nginx.html

**Comment by vrkansagara** [comment]
> 2. Configure as a service with systemctl or with @vrkansagara's guide

@PGimenez  is referring [to this link](https://github.com/GenieFramework/Genie.jl/pull/668/files), If any interested to read
