### ISSUE TITLE
broken link in reference index page

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/GenieFrameworkDocs#4]
The server link in /docs/reference/overview does not work, 404

**Comment by ms10596** [comment]
I can work on it today @PGimenez

**Comment by PGimenez** [comment]
@ms10596 thanks but apparently this is already fixed😅. We used to have the site on a /docs subfolder but the link works now that it's a subdomain.

**Comment by ms10596** [comment]
Should we open another issue the fact that [this link](https://learn.genieframework.com/reference/overview/server/) is not working

**Comment by PGimenez** [comment]
@ms10596 done in https://github.com/GenieFramework/GenieFrameworkDocs/issues/44
