### ISSUE TITLE
Add Discord forum page

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/GenieFrameworkDocs#46]
We have a lot of questions in the Discord server that are not reachable via search engines. We should export the forum threads and add them to a page in the docs so that people can at least read them. If they want to participate, then a link should direct them to the thread.

We could use this to export the forum https://github.com/Tyrrrz/DiscordChatExporter

**Comment by ms10596** [comment]
The current situation is as follows:
* We mainly need to export channel `help-forum`.
* DiscordChatExporter cannot find any messages in the channel. I suppose that's because it's a special kind of channel (forum).
* Will dive deeper to see if there are other ways to export that channel
* To replicate I used that command
```bash
docker run --rm -it tyrrrz/discordchatexporter:latest export -c 1032309299512344626 -t token
```

**Comment by PGimenez** [comment]
Apparently this is [not supported](https://github.com/Tyrrrz/DiscordChatExporter/issues/1100) but they're [working on it](https://github.com/Tyrrrz/DiscordChatExporter/issues/1119)

We can also try the `discord`module for Python. I played around with it a while ago to sync the forum with Jira issues and it worked well

```python
import discord
from jira import JIRA

class MyClient(discord.Client):
    async def on_ready(self):
        print(f'Logged in as {self.user} (ID: {self.user.id})')
        print('------')

    async def on_message(self, message):
        if message.author.id == self.user.id:
            return

        if message.content.startswith('!hello'):
            await message.reply('Hello!', mention_author=True)

    async def on_thread_create(self, thread):
        if thread.parent.name == "help-forum":
            messages = [message async for message in thread.history(limit=1)]
            title = thread.name
            description = messages[0].content+"\n"+thread.jump_url
            create_jira_issue(server_url, username, password, project_key, title, description)

def create_jira_issue(server, username, password, project_key, title, description):
    jira = JIRA(server, basic_auth=(username, password))
    
    issue_fields = {
        "project": {"key": project_key},
        "summary": title,
        "description": description,
        "issuetype": {"name": "Task"},
    }
    
    new_issue = jira.create_issue(fields=issue_fields)
    print(f"Created issue {new_issue.key} with title '{title}' and description '{description}'")

if __name__ == "__main__":
    server_url = "https://.atlassian.net"
    username = "pere@.app"
    password = ""
    project_key = "DA"

    intents = discord.Intents.default()
    intents.message_content = True

    client = MyClient(intents=intents)
    client.run('token')

```

**Comment by ms10596** [comment]
I've checked [discordpy](https://discordpy.readthedocs.io/en/stable/). I managed to make a bot that reads the historical messages of the channel. However, I could retrieve text messages only and I couldn't retrieve forum messages.

Anyway, I managed to retrieve all 26 threads in `help-forum`. Now I have them in both `.html` & `.json`. JSON contains more details but HTML provides a nice UI out of the box. I'll attach examples for both and we can discuss how we can proceed. 
[Genie Community - help-forum - Update @in var1 when @in var2 changes [1144658552401711116].zip](https://github.com/GenieFramework/GenieFrameworkDocs/files/12506148/Genie.Community.-.help-forum.-.Update.%40in.var1.when.%40in.var2.changes.1144658552401711116.zip)

**Comment by PGimenez** [comment]
This is great! I think the JSON is better as it is easier to manipulate. I've created a new branch https://github.com/GenieFramework/GenieFrameworkDocs/pull/56 with a new page /forum to render the thread.

<img width="1316" alt="Screenshot 2023-09-04 at 12 26 44" src="https://github.com/GenieFramework/GenieFrameworkDocs/assets/5058397/6b27b696-11cb-4940-be72-68a96eae0b87">

When you click on the username it links to you to the message on Discord, which is nice. 

I'm having some issues deploying the preview on Netlify, but it should work locally.

**Comment by PGimenez** [comment]
Yes we'd need an `index.vue`page to list the threads, and a `[thread].vue` page to dynamically display the threads. Similar to what we have in the app gallery. I've updated the page styles and added the dynamic page and index
