### ISSUE TITLE
Fix @ref links in API docs

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/GenieFrameworkDocs#55]
Apparently Documenter.jl  adds a link whenever a type appears, like [`Integer`](@ref). We have to remove these links or fix them.

**Comment by ms10596** [comment]
Yeah, It does happen a lot and it's a source of 404. Check my last [pull request](https://github.com/GenieFramework/GenieFrameworkDocs/pull/52)

**Comment by PGimenez** [comment]
I'm going to rebuild the API docs soon, I'll fix it then.
