### ISSUE TITLE
Redirect old docs pages to current site

### ISSUE THREAD

**Issue by PGimenez** [GenieFramework/GenieFrameworkDocs#76]
There's several pages at 
https://geniejl.readthedocs.io/
https://genieframework.github.io/

That need to be redirected to learn.genieframework.com

Also, need to add a warning to genieframework.com/docs telling users to check out the new docs

**Comment by essenciary** [comment]
How? Do the pages have the same URL structure? Or what's the rule?

**Comment by PGimenez** [comment]
I was thinking about redirecting all queries regardless of path to learn.genieframework.com. We'd probably take a pagerank hit as these old doc pages would eventually disappear, but I can't think of other options besides manually redirecting every single page.

**Comment by essenciary** [comment]
OK - I need to check what redirection options are provided by readthedocs and github.io.
